// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260101235551_MakeBirdCommonNameNullable")]
    partial class MakeBirdCommonNameNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "bob-id",
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = "shane-id",
                            UserName = "Shane"
                        },
                        new
                        {
                            Id = "john-id",
                            UserName = "John"
                        });
                });

            modelBuilder.Entity("API.Entities.Bird", b =>
                {
                    b.Property<string>("SpeciesCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommonName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScientificName")
                        .HasColumnType("TEXT");

                    b.HasKey("SpeciesCode");

                    b.ToTable("Birds");
                });

            modelBuilder.Entity("API.Entities.UserBird", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeciesCode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Found")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WantToSee")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "SpeciesCode");

                    b.HasIndex("SpeciesCode");

                    b.HasIndex("UserId");

                    b.ToTable("UserBirds");
                });

            modelBuilder.Entity("API.Entities.UserBird", b =>
                {
                    b.HasOne("API.Entities.Bird", "Bird")
                        .WithMany("UserBirds")
                        .HasForeignKey("SpeciesCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.AppUser", "User")
                        .WithMany("UserBirds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bird");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Navigation("UserBirds");
                });

            modelBuilder.Entity("API.Entities.Bird", b =>
                {
                    b.Navigation("UserBirds");
                });
#pragma warning restore 612, 618
        }
    }
}
